### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#1]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Navigation & Authentication  |
| Epic | Navigation & Authentication |
| User Story | Navigation |

## Description
As a **user**, I can **view a navigation bar** on every page so that I can **navigate easily between the pages of the website**

## Acceptance Criteria
1. The user can view a navigation bar.
2. The user can navigate through the website using the navigation bar.

## Tasks
- [x] Create a navigation bar and display it on all the pages.
- [x] Implement the functionality of the navigation bar.
- [x] Make sure the user can navigate easily.
