### ISSUE TITLE
Like a review

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#13]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Adding & Liking Reviews  |
| Epic | Adding & Liking Reviews |
| User Story | Like a review |

## Description
As a **logged-in user**, I can **like a review** so that **I can show my support for the reviews that interest me**

## Acceptance Criteria
1. A logged-in user can like a review that he/she finds interesting
2. The like is displayed alongside the liked review

## Tasks
- [x] The logged-in user can like a particular review
- [x] The like count is increased after each like
- [x] The likes are displayed alongside the liked review
