### ISSUE TITLE
View most recent books

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#14]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | All Books Page  |
| Epic | All Books Page |
| User Story | View most recent books |

## Description
As a **user** I can **view all the most recent books** ordered by the most recently created first so that **I am up to date with the newest content**

## Acceptance Criteria
1. The user can view all the most recent books
2. The most recent books are ordered by the date of creation
3. The user is up to date with the latest content on the website

## Tasks
- [x] The most recent books are loaded for the user
- [x] The loaded content is ordered by the date of creation
- [x] The user can be up to date with the latest content
