### ISSUE TITLE
Search with keywords

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#15]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | All Books Page  |
| Epic | All Books Page |
| User Story | Search with keywords |

## Description
As a **user** I can **search for books with keywords** so that **I can find the books and user profiles I am most interested in**

## Acceptance Criteria
1. The user can search with keywords
2. The search results are displayed properly based on the keywords
3. The user can find the books and user profiles as per their search preferences

## Tasks
- [x] Search bar is visible for the user
- [x] Implement the search with keyword functionality 
- [x] Display the search results
- [x] The user can find the appropriate books and user profiles as per their search preferences
