### ISSUE TITLE
View reviews of followed users

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#17]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | All Books Page  |
| Epic | All Books Page |
| User Story | View reviews of followed users |

## Description
As a **logged-in user** I can **view content filtered by users I follow** so that **I can keep up to date with what they are posting about**

## Acceptance Criteria
1. The logged-in user can view content filtered by the users he/she follows
2. The user is presented with relevant content so that they can keep up-to-date

## Tasks
- [x] Verify the user is logged in
- [x] Display the content relevant to them by filtering with followed user profiles
- [x] The user can be up to date with what they are posting about
