### ISSUE TITLE
View book details page

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#19]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Book Details Page  |
| Epic | Book Details Page |
| User Story | View book details page |

## Description
As a **user** I can **view the book details page** so that **I can read the details about the book**

## Acceptance Criteria
1. The user can view the book details page
2. The book details page displays all the details about the book

## Tasks
- [x] The user can click on a particular book for details
- [x] The book details are fetched and displayed
- [x] The user can read everything about the book
- [x] The user can understand more about the books they are interested in
