### ISSUE TITLE
Create a comment

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#21]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Book Details Page  |
| Epic | Book Details Page |
| User Story | Create a comment |

## Description
As a **logged-in user** I can **add comments to a review** so that **I can share my thoughts about the review**

## Acceptance Criteria
1. The logged-in user can add comments to a review
2. The newly added comments are displayed alongside the review
3. The comment has details like the owner's name and added date

## Tasks
- [x] The logged-in user can add a comment
- [x] The comment is displayed with the review
- [x] The comment has owner's name and created date
