### ISSUE TITLE
Delete comments

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#24]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Book Details Page  |
| Epic | Book Details Page |
| User Story | Delete comments |

## Description
As an **owner of a comment**  I can **delete my comment** so that **I can control the removal of my comment from the application**

## Acceptance Criteria
1. The owner of a comment can delete a previously added comment
2. The user is prompted with a confirmation message before the actual deletion happens
3. Other users cannot delete the comment added by another user

## Tasks
- [x] Verify the logged-in user is the actual owner of the comment
- [x] The owner can delete his/her comment
- [x] Display a confirmation message before deletion
- [x] Delete the comment and provide a feedback message
