### ISSUE TITLE
Edit a comment

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#25]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Book Details Page  |
| Epic | Book Details Page |
| User Story | Edit a comment |

## Description
As an **owner of a comment** I can **edit my comment** so that **I can fix or update my existing comment**

## Acceptance Criteria
1. The owner of a comment can edit comments added by them
2. The existing comment is updated with the edited comment
3. No one other than the owner of the comment can update it

## Tasks
- [x] Verify that the logged-in user is the owner of the comment
- [x] The owner can update an existing comment
- [x] The updated comment is saved
- [x] The updated comment is displayed
