### ISSUE TITLE
Most followed profiles

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#27]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Profile Page  |
| Epic | Profile Page |
| User Story | Most followed profiles |

## Description
As a **user** I can **see the list of the most followed profiles** so that **I can see which are the popular profiles**

## Acceptance Criteria
1. The user can see the list of the most followed profiles

## Tasks
- [x] Make the list of the most followed profiles
- [x] Make this list available to the user
- [x] The user can see which are the popular profiles
