### ISSUE TITLE
Follow/Unfollow a user

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#29]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Profile Page  |
| Epic | Profile Page |
| User Story | Follow/Unfollow a user |

## Description
As a **logged-in user**  I can **follow and unfollow other users** so that **I can see and remove reviews by specific users in my feed**

## Acceptance Criteria
1. The logged-in user can follow and unfollow other users
2. The reviews appearing on a user's feed are filtered as per his follow/unfollow preferences

## Tasks
- [x] Verify the user is logged in
- [x] If logged in, he/she can follow other users they find interesting
- [x] Also, if they are not interested in a particular profile, they can unfollow it
- [x] The reviews appearing on a user's feed are filtered as per his follow/unfollow preferences
