### ISSUE TITLE
Authentication - Sign up

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#3]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Navigation & Authentication |
| Epic | Navigation & Authentication |
| User Story | Authentication - Sign up |

## Description
As a **user** I can **create a new account** so that **I can access all the website features**.

## Acceptance Criteria
1. The user can create a new account by registering with a username and password.
2.  The registered user can access the website features.

## Tasks
- [x] Set up authentication for user sign-up
- [x] The user enters a username and password
- [x] The registered user can access the website
- [x] The user credentials are stored for future logins
