### ISSUE TITLE
Edit profile

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#31]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Profile Page  |
| Epic | Profile Page |
| User Story | Edit profile |

## Description
As a **logged-in user**, I can **edit my profile** so that **I can change my profile details**

## Acceptance Criteria
1. The logged-in users can edit their profiles
2. Users cannot edit profiles other than their own

## Tasks
- [x] Verify the user is logged in
- [x] The logged-in user can edit their profile
- [x] The edited details are updated on their profile
