### ISSUE TITLE
Update username and password

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#32]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Profile Page  |
| Epic | Profile Page |
| User Story | Update username and password |

## Description
As a **logged-in user**  I can **update my username and password** so that **I can change my display name and keep my profile secure**

## Acceptance Criteria
1. The logged-in users can update their login credentials: username and password
2. The updated details are displayed on their profile

## Tasks
- [x] Verify the user is logged in
- [x] The logged-in user can update their credentials
- [x] The credentials include a username and password linked to a profile
- [x] The updated details are displayed on the respective profile
