### ISSUE TITLE
Mock Testing

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#33]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Testing & Validation  |
| Epic | Testing & Validation |
| User Story | Mock Testing |

## Description
**As a **developer** I want **to add mock tests** so that **I can implement automation testing**

## Acceptance Criteria
1. Mock test cases are written for specific test cases
2. All the test cases are passing while running the tests

## Tasks
- [x] Write mock tests
- [x] Run the tests
- [x] Ensure all the tests are PASSED
