### ISSUE TITLE
Manual Testing

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#34]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme |  Testing & Validation |
| Epic | Testing & Validation |
| User Story | Manual Testing |

## Description
As a **developer** I want **to test all the user stories manually** so that **I can validate all the features and functionalities**

## Acceptance Criteria
1. All the user stories are tested and validated manually
2. All the features and functionalities are working as expected

## Tasks
- [x] Manually test each user story
- [x] The acceptance criteria are met for all the user stories
- [x] Validate all the features and functionalities are working as expected
