### ISSUE TITLE
Documentation (README file) for front end

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#35]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Documentation  |
| Epic | Documentation |
| User Story | Documentation (README file) for front end |

## Description
As a **developer** I want **to document everything in the README file** so that **it can be used to understand the project and also for future reference and improvements**

## Acceptance Criteria
1. The project is documented well in the README file
2. The README file is complete with all the required details

## Tasks
- [x] Create a README file using the markdown template
- [x] The README file is structured properly with relevant sections
- [x] Content and screenshots are added for all the sections
- [x] README is completed and can be used for future references
