### ISSUE TITLE
Authentication - Sign in

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#4]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Navigation & Authentication  |
| Epic | Navigation & Authentication |
| User Story | Authentication - Sign in |

## Description
As a **user** I can **sign in to the website** so that I can **access all the functionalities for logged-in users**

## Acceptance Criteria
1. The users can sign in to the website using their credentials.
2. The users can access all the functionalities for logged-in users.

## Tasks
- [x] Create a log-in form that accepts username and password. 
- [x] Verify the entered credentials and log in the users with the correct credentials.
- [x] The logged-in users can access all the functionalities.
