### ISSUE TITLE
Authentication - Refreshing access tokens

### ISSUE THREAD

**Issue by arathivariar** [arathivariar/book-nook#6]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Theme | Navigation & Authentication  |
| Epic | Navigation & Authentication |
| User Story | Authentication - Refreshing access tokens |

## Description
As a **user** I can **maintain my logged-in status until I choose to log out** so that **my user experience is not compromised**

## Acceptance Criteria
1. The user can maintain his/her logged-in status
2. The access tokens for a logged-in user are refreshed

## Tasks
- [x] Implement the access tokens refresh for logged-in users
- [x] The user's logged-in status is maintained
- [x] Ensure a good user experience
- [x] The user can log out without issues whenever he/she chooses to.
